---
title: "Governo e Economia"
author: "Natália Tosi"
date: "8/25/2021"
output: pdf_document
---

```{r message = FALSE, warning = FALSE, include = FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center",
  fig.width = 8, 
  fig.height = 4
  )

options(scipen = 999)

library(tidyverse)
library(broom)
library(lubridate)
library(scales)

```

```{r}

ipca <- read_csv("ipca.csv") %>%
  mutate(date = my(date))

pib <- read_csv("gdp.csv") %>%
  mutate(date = my(date))

aprov <- read_csv("agregador.csv") %>%
  mutate(date = ym(date))

```

```{r}

agregado <- left_join(aprov, ipca, by = c("date" = "date")) %>%
  left_join(pib, by = c("date" = "date"))

agregado <- agregado %>%
  mutate(month1 = month(date),
         year1 = year(date),
         quarter = case_when(
           month1 %in% c(1:3) ~ 1,
           month1 %in% c(4:6) ~ 2,
           month1 %in% c(7:9) ~ 3,
           month1 %in% c(10:12) ~ 4)) %>%
  filter(date >= as.Date("1995-01-01"))

data_clean <- agregado %>%
  group_by(month1, year1, quarter) %>%
  summarise(pib1 = mean(gdp, na.rm = TRUE),
            ipca = mean(ipca, na.rm = TRUE),
            aprov = mean(latentM, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(quarter, year1) %>%
  mutate(pib = mean(pib1, na.rm = TRUE),
         date = make_date(year1, month1)) %>%
  ungroup()

data_clean <- data_clean %>%
  mutate(pib_rescaled = rescale(pib, to = c(0,100), 
                        from = range(pib, na.rm = TRUE, finite = TRUE)),
         
         ipca_rescaled = rescale(ipca, to = c(0,100), 
                        from = range(ipca, na.rm = TRUE, finite = TRUE)),
         
         aprov_rescaled = rescale(aprov, to = c(0,100), 
                        from = range(aprov, na.rm = TRUE, finite = TRUE)))

```

```{r}

data_clean %>% 
  ggplot(aes(x = date, y = aprov)) +
  geom_line(aes(color = aprov, color = "black"), color = "black") +
  geom_line(aes(y = pib_rescaled, color = pib_rescaled), linetype = "dashed", 
            color = "darkblue") +
  labs(x = "Data", y = "Aprov/Escala",
       title = "Aprovação de Governo Vs PIB") +
   theme(plot.title = element_text(color = "grey13", size = 16, face = "bold", 
                                  hjust = 0.5)) +
  geom_vline(color = "grey", xintercept = c(
           as.Date("2002-10-01"),
           as.Date("2006-10-01"),
           as.Date("2010-10-01"),
           as.Date("2014-10-01"),
           as.Date("2016-09-01"),
           as.Date("2018-10-01"))) +
  annotate("text", x = as.Date("2000-01-01"), y = 100, label = "FHC", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2005-01-01"), y = 100, label = "Lula", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2009-01-01"), y = 100, label = "Lula", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2013-01-01"), y = 100, label = "Dilma", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2015-09-01"), y = 100, label = "Dilma", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2017-09-01"), y = 100, label = "Temer", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2020-06-01"), y = 100, label = "Bolsonaro", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2018-06-01"), y = 60, label = "PIB (escala 0 a 100)", 
           alpha = 1, fontface = 2, color = "darkblue") +
  annotate("text", x = as.Date("2005-06-01"), y = 20, label = "Aprovação", 
           alpha = 1, fontface = 2, color = "black")

```


```{r}

data_clean %>% 
  ggplot(aes(x = date, y = aprov)) +
  geom_line(aes(color = aprov), color = "black") +
  geom_line(aes(y = ipca_rescaled, color = ipca_rescaled), linetype = "dashed", 
            color = "darkred") +
  labs(x = "Data", y = "Aprov/Escala",
       title = "Aprovação de Governo Vs IPCA (Escala 0 a 100)") +
   theme(legend.position = "top",
         plot.title = element_text(color = "grey13", size = 16, face = "bold", 
                                  hjust = 0.5)) +
  geom_vline(color = "grey", xintercept = c(
           as.Date("2002-10-01"),
           as.Date("2006-10-01"),
           as.Date("2010-10-01"),
           as.Date("2014-10-01"),
           as.Date("2016-09-01"),
           as.Date("2018-10-01"))) +
  annotate("text", x = as.Date("2000-01-01"), y = 100, label = "FHC", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2005-01-01"), y = 100, label = "Lula", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2009-01-01"), y = 100, label = "Lula", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2013-01-01"), y = 100, label = "Dilma", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2015-09-01"), y = 100, label = "Dilma", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2017-09-01"), y = 100, label = "Temer", 
           alpha = 1, fontface = 2) +
  annotate("text", x = as.Date("2020-06-01"), y = 100, label = "Bolsonaro", 
           alpha = 1, fontface = 2) +
   annotate("text", x = as.Date("2010-06-01"), y = 10, label = "IPCA (escala 0 a 100)", 
           alpha = 1, fontface = 2, color = "darkred") +
  annotate("text", x = as.Date("2010-06-01"), y = 65, label = "Aprovação", 
           alpha = 1, fontface = 2, color = "black")

```



